# Generated by Django 5.2.1 on 2025-09-14 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployee',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(db_column='Brand_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Brand_Name', max_length=100)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='Category_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Category_Name', max_length=100)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_id', models.AutoField(db_column='Condition_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Condition_Name', max_length=50)),
            ],
            options={
                'db_table': 'condition_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='Customer_Name', max_length=255)),
                ('contact_number', models.CharField(db_column='Contact_Number', max_length=50)),
                ('address_id', models.IntegerField(blank=True, db_column='Address_ID', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('confirmed', models.BooleanField()),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=16)),
                ('valid_until', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('throttling_failure_count', models.PositiveIntegerField(blank=True, null=True)),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_generated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_email_emaildevice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='Product_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Product_Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Product_Description')),
                ('purchase_price', models.DecimalField(db_column='Purchase_Price', decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(db_column='Selling_Price', decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(db_column='Sale_ID', primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(blank=True, db_column='Total_Amount', null=True)),
                ('payment_type', models.CharField(blank=True, db_column='Payment_Type', max_length=255, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('sale_detail_id', models.AutoField(db_column='Sale_Detail_ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('selling_price', models.IntegerField(blank=True, db_column='Selling_Price', null=True)),
                ('sub_total', models.IntegerField(blank=True, db_column='Sub_total', null=True)),
            ],
            options={
                'db_table': 'sale_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(db_column='Supplier_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Supplier_Name', max_length=255)),
                ('contact_number', models.CharField(db_column='Contact_Number', max_length=50)),
                ('address', models.CharField(db_column='Address', max_length=255)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.AutoField(db_column='Supply_ID', primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(db_column='Total_Cost', decimal_places=2, max_digits=12)),
                ('receipt_number', models.CharField(db_column='Receipt_Number', max_length=100)),
                ('date', models.DateField(db_column='Date')),
            ],
            options={
                'db_table': 'supply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'supply_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_otp',
                'managed': True,
            },
        ),
    ]
