# Generated by Django 5.2.1 on 2025-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(db_column='Brand_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Brand_Name', max_length=100)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='Category_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Category_Name', max_length=100)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_id', models.AutoField(db_column='Condition_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Condition_Name', max_length=50)),
            ],
            options={
                'db_table': 'condition_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6 digit code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'email_otp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='Product_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Product_Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Product_Description')),
                ('purchase_price', models.DecimalField(db_column='Purchase_Price', decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(db_column='Selling_Price', decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(db_column='Supplier_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Supplier_Name', max_length=255)),
                ('contact_number', models.CharField(db_column='Contact_Number', max_length=50)),
                ('address', models.CharField(db_column='Address', max_length=255)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.AutoField(db_column='Supply_ID', primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(db_column='Total_Cost', decimal_places=2, max_digits=12)),
                ('receipt_number', models.CharField(db_column='Receipt_Number', max_length=100)),
                ('date', models.DateField(db_column='Date')),
            ],
            options={
                'db_table': 'supply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'supply_details',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='useremployee',
            options={'managed': False},
        ),
    ]
