# Generated by Django 5.2.1 on 2025-06-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_category_condition_emailotp_product_roletype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useremployee',
            table='user_employee',
        ),
    ]
