# Generated by Django 5.2.1 on 2025-06-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_useremployee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='Customer_Name', max_length=255)),
                ('contact_number', models.CharField(db_column='Contact_Number', max_length=50)),
                ('address_id', models.IntegerField(blank=True, db_column='Address_ID', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('confirmed', models.BooleanField()),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=16)),
                ('valid_until', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('throttling_failure_count', models.PositiveIntegerField(blank=True, null=True)),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_generated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_email_emaildevice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(db_column='Sale_ID', primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(blank=True, db_column='Total_Amount', null=True)),
                ('payment_type', models.CharField(blank=True, db_column='Payment_Type', max_length=255, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('sale_detail_id', models.AutoField(db_column='Sale_Detail_ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('selling_price', models.IntegerField(blank=True, db_column='Selling_Price', null=True)),
                ('sub_total', models.IntegerField(blank=True, db_column='Sub_total', null=True)),
            ],
            options={
                'db_table': 'sale_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_otp',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
