# Generated by Django 5.2.1 on 2025-06-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_emaildevice_sale_saledetails_userotp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userotp',
            options={'managed': True},
        ),
    ]
